Multiple user types
josh-velasquez/Twijj pull request #37
Opened 2020-04-03 23:49 UTC by josh-velasquez

Updates:
- Created new user called admin that can delete any stream
- Updated the side nav bar by using icon instead of image and shrinking the size of the sub profiles
- Fixed the gear icon colouring

2020-04-06 16:00 UTC, emilio-alvarez requested changes

2020-04-06 16:00 UTC, emilio-alvarez commented on client/src/components/profile/Profile.js
> +import { fetchProfile ,fetchAdmins} from "../../actions";
Was this added accidentally? It's giving a warning in the console since it's never used in this file.

2020-04-06 16:00 UTC, emilio-alvarez commented on client/src/components/streams/StreamList.js
> +        this.props.admins.filter(
You probably want to add `.length != 0` at the end of this.

Filter returns an empty array if no element is found, so this will always evaluate to true. I'm not an admin, but the button shows up for me.

2020-04-06 23:25 UTC, josh-velasquez commented on client/src/components/profile/Profile.js
> +import { fetchProfile ,fetchAdmins} from "../../actions";
Yeah, this was imported by accident and I forgot to remove it. I updated it with this removed and this file formatted.

2020-04-06 23:26 UTC, josh-velasquez commented on client/src/components/streams/StreamList.js
> +        this.props.admins.filter(
Dang good catch! I forgot to add the .length check since it returns the id if it is found. Updated this on my commit

2020-04-07 00:59 UTC, emilio-alvarez approved these changes

2020-04-07 00:59 UTC, merged